### ISSUE TITLE
Initial devnet DALC Implementation

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/dalc#1]
It was decided in [#142](https://github.com/celestiaorg/optimint/issues/142) that we will separate out the data availability light client from optimint and into it's own repo. Fortunately, a sizable chunk of the core logic needed for the first devnet implementation has already been written. However, there is still some work needed to be done. Notably, we still need a to query application specific data (see our old planned [implementation](https://github.com/renaynay/celestia-core/blob/retrieve-app-messages-ismail/p2p/ipld/retrieve.go)), and decide precisely how we plan on performing DAS (see old [`ValidateAvailability`](https://github.com/celestiaorg/celestia-core/blob/c4f2a98f4928d3b04517621c5792744c106ba306/pkg/da/ipld/validate.go) func)

- [x] #11 
- [x] #3
- [x] #4
- [ ] #5 
- [ ] #6

**Comment by tzdybal** [comment]
Replaced by #25.
