### ISSUE TITLE
Client code to submit block

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/dalc#4]
We will need to be able to submit blocks to celestia for optimint. Most of the this code has already been written, we just have to plug it into the rest of the DALC. See [old optimint code](https://github.com/celestiaorg/optimint/blob/eea0a826478f926341e8e664d405a2056fde0aeb/da/celestia/celestia.go) and app's [client code](https://github.com/celestiaorg/lazyledger-app/blob/master/x/payment/types/builder.go).

**Comment by tzdybal** [comment]
Resolved by #12.
