### ISSUE TITLE
Add ability to query application specific data

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/dalc#6]
Per the original [ADR](https://github.com/celestiaorg/celestia-core/blob/master/docs/celestia-architecture/adr-003-application-data-retrieval.md) in the celestia-core, we need to have the ability to retrieve the data from a specific namespace for a given block. We had planned a previous implementation [here](https://github.com/renaynay/celestia-core/blob/retrieve-app-messages-ismail/p2p/ipld/retrieve.go), but our plans were in limbo and we never completed it. Further discussion is needed as to exactly how we should implement this functionality, and in which repo the implementation should reside.

**Comment by tzdybal** [comment]
Resolved by #17
